source $VIMRUNTIME/defaults.vim

" settings
set guicursor=n-v-c:block,o:hor50,i-ci:hor15,r-cr:hor30,sm:block
set mouse=
set number
set relativenumber
set showmatch
set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab
set autoindent
set wrap
set linebreak
set nolist
set breakindent
set scrolloff=18
set laststatus=2
